player/src/main/kotlin/com/globo/clappr/base/Events.kt
player/src/main/kotlin/com/globo/clappr/base/InternalEvents.kt
player/src/main/kotlin/com/globo/clappr/components/Container.kt
player/src/main/kotlin/com/globo/clappr/components/Core.kt
player/src/main/kotlin/com/globo/clappr/components/Playback.kt
player/src/main/kotlin/com/globo/clappr/plugin/Loader.kt
player/src/test/kotlin/com/globo/clappr/com/globo/clappr/components/ContainerTest.kt
player/src/test/kotlin/com/globo/clappr/com/globo/clappr/components/CoreTest.kt
player/src/test/kotlin/com/globo/clappr/plugin/LoaderTest.kt

. Split internal and external events
. Add Playback events and error state
. Add new triggers for playback and container changes

Internal events

---

clappr/src/main/kotlin/io/clappr/player/Player.kt
clappr/src/test/java/io/clappr/player/PlayerJavaTest.java
clappr/src/test/kotlin/io/clappr/player/PlayerTest.kt

Change load to reconfigure player

---

clappr/src/main/kotlin/io/clappr/player/Player.kt

Make title visible on full screen

fix(video_info): Make title visible on full screen

---

clappr/src/main/kotlin/io/clappr/player/Player.kt

feat(cofigure_visibility): make configure method open

---

build.gradle

Goal 
Update Kotlin to the newest version
Test
See if our project is using the lasted kotlin version (1.2.30)

feat(kotlin_upgrade) Upgrading kotlin version

---

build.gradle

Upgrade android support version to latest.
1. Open clappr-android/app
2. Execute any video and do play, pause, resume and stop.

feat(upgrade_android_support) Upgrade android support version to latest.

---

clappr/build.gradle
clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt

Update ExoPlayer (base for `ExoPlayerPlayBack`) to the latest version: [2.7.3](https://github.com/google/ExoPlayer/releases).
- Run all tests
- Play, pause, resume video

Update Exoplayer to 2.7.3

---

clappr/src/main/kotlin/io/clappr/player/components/Container.kt

Fix the issue [#54](https://github.com/globoi/player-android-releases/issues/54).
1 - Run the app
2 - Click on "next" and "previous" many times, playing many videos.

Error on continue play

---

clappr/src/main/kotlin/io/clappr/player/log/LogLevel.kt

Remove warnings from Logger class.

refactor(remove_warnings): remove Logger warnings

---

app/src/main/res/values/strings.xml

One little PR to a great event.

refactor(remove_lint): remove Hello Word string

---

app/build.gradle
build.gradle
clappr/build.gradle
gradle/wrapper/gradle-wrapper.properties

Goal: Update gradle to verion 4.5.

feat(update_gradle): Update gradle to version 4.5

---

build.gradle

Update Kotlin runtime with last AndroidStudio GradlePlugin. We are having severals issues when fresh cloning andy repository and running tests.
1 - Press `Command+Shift+a` and type `kotlin SDK`
2 - Select `Configure Kotlin Plugin Updates`
3 - Click on `Recheck now` and mare sure that you have latest updates
4 - Press `Command+Shift+a` and type `Plugins`
5 - Type `Kotlin` on filter and make sure that you have the latests Kotlin plugin update.
6 - Open Plugins e make that all is compiling without error.
7 - Run tests and make sure that you have all green

chore(update_kotlin): update kotlin to version 1.2.50

---

clappr/src/main/kotlin/io/clappr/player/components/Playback.kt
clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt

Make public the Exoplayer window start through the `currentDate` parameter.

Make public the Exoplayer window start

---

clappr/src/main/kotlin/io/clappr/player/plugin/ButtonPlugin.kt
clappr/src/main/kotlin/io/clappr/player/plugin/Control/ButtonPlugin.kt

Create Button plugin

---

clappr/src/main/kotlin/io/clappr/player/extensions/doubleExtensions.kt
clappr/src/main/kotlin/io/clappr/player/plugin/Control/TimeIndicatorPlugin.kt
clappr/src/main/kotlin/io/clappr/player/plugin/PluginConfig.kt
clappr/src/main/res/layout/time_indicator.xml
clappr/src/main/res/values/colors.xml
clappr/src/main/res/values/dimens.xml
clappr/src/test/kotlin/io/clappr/player/extensions/DoubleExtensionsTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/Control/TimeIndicatorPluginTest.kt

Create Time Indicator Plugin
3 - Check if Time Indicator is appearing in the video

Time Indicator Plugin

---

clappr/src/main/kotlin/io/clappr/player/plugin/Control/SeekbarPlugin.kt
clappr/src/main/kotlin/io/clappr/player/plugin/PluginConfig.kt
clappr/src/main/res/drawable/scrubber_circle.xml
clappr/src/main/res/layout/seekbar_plugin.xml
clappr/src/main/res/values/colors.xml
clappr/src/main/res/values/dimens.xml
clappr/src/test/kotlin/io/clappr/player/plugin/Control/SeekbarPluginTest.kt
clappr/src/test/kotlin/io/clappr/player/shadows/ClapprShadowView.kt

Create Seekbar Plugin
3 - Check if seekbar is appearing in the video
4 - Perform a seek to check if is working

Seekbar Plugin

---

clappr/src/test/kotlin/io/clappr/player/plugin/LoadingPluginTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/PosterPluginTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/UIPluginTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/FullscreenButtonTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/PlayButtonTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/SeekbarPluginTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/TimeIndicatorPluginTest.kt

Goal
--
Add tests for after-destroy scenary
How to test
---
- Run `.\gradlew test`

test/listeners: add tests for destroy

---

README.md
build.gradle

Goal
---
Update kotlin to 1.2.71
Hos to test
---
- Run app
- Run `./gradlew test`

feat/kotlin_update: update to 1.2.71

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt

Prevent Player crash when DRM Exceptions is thrown during DRM Session Manager creation
1 - Open sample app
2 - Check if video is playing correctly

Prevent Player crash when DRM Exceptions is thrown

---

clappr/src/main/kotlin/io/clappr/player/Player.kt

Goal
---
Change playback and container events list visibility in Player
How to test
---
1 - Run Unit tests
3 - Check if video everything is working correctly, play/pause the video, perform seek, wait for it to finish and play it again, go fullscreen and back to portrait

Make Playback and Container Events List Private

---

clappr/src/main/kotlin/io/clappr/player/Player.kt
clappr/src/test/kotlin/io/clappr/player/PlayerTest.kt

Goal
Change core visibility in player
How to test
1 - Run Unit tests
3 - Check if video everything is working correctly, play/pause the video, perform seek, wait for it to finish and play it again, go fullscreen and back to portrait

Change core visibility in player

---

clappr/src/main/kotlin/io/clappr/player/plugin/PosterPlugin.kt
clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/main/kotlin/io/clappr/player/plugin/control/PlayButton.kt
clappr/src/main/kotlin/io/clappr/player/plugin/control/SeekbarPlugin.kt
clappr/src/main/kotlin/io/clappr/player/plugin/control/TimeIndicatorPlugin.kt
clappr/src/test/kotlin/io/clappr/player/plugin/PosterPluginTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/PlayButtonTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/SeekbarPluginTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/TimeIndicatorPluginTest.kt
clappr/src/test/kotlin/io/clappr/player/shadows/ShadowUri.kt

Goal
---
Change visibility of some methods and variables in Plugins
How to test
---
1 - Run Unit tests
3 - Check if video everything is working correctly, play/pause the video, perform seek, wait for it to finish and play it again, go fullscreen and back to portrait

Change visibility of some methods and variables in Plugins

---

clappr/build.gradle
clappr/src/test/kotlin/io/clappr/player/plugin/control/SeekbarPluginTest.kt

Update Robolectric version to `3.8`

fix(adjust_robolectric_version): Upgrade roboelectric version

---

README.md
app/build.gradle
clappr/build.gradle

Update exoplayer version to `2.9.2`

chore(exoplayer_2_9_2): update Exoplayer to version 2.9.2

---

build.gradle

Update Kotlin to version 1.3.21

Update Kotlin to version 1.3.21

---

clappr/src/main/kotlin/io/clappr/player/base/Options.kt
clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerPlayBackTest.kt
clappr/src/test/kotlin/io/clappr/player/shadows/SimpleExoplayerShadow.kt

To have a better experience with the player. We are implement the capability to play a video in a loop.
1. Go to `PlayerActivity.loadVideo()` and add this line of code `options[ClapprOption.LOOP.value] = true`
2. Run the app and checks if the video starts again without any stalled time.
3. Repeat the test before change the value to `false`, to an invalid value as `"invalid"` and not sending the `ClapprOption.LOOP` and check if the video stops after ends

Video loop

---

doc/clappr/io.clappr.player.base/-clappr-option/-l-o-o-p.md
doc/clappr/io.clappr.player.base/-event/-m-e-d-i-a_-o-p-t-i-o-n-s_-u-p-d-a-t-e.md
doc/clappr/io.clappr.player.base/-internal-event/-d-i-d_-r-e-s-i-z-e.md
doc/clappr/io.clappr.player.components/-playback/media-options-array-json.md
doc/clappr/io.clappr.player.components/-playback/media-options-name-json.md
doc/clappr/io.clappr.player.components/-playback/media-options-type-json.md

Update Clappr dokka documentation

Update Dokka Documentation

---

clappr/src/main/kotlin/io/clappr/player/base/InternalEvents.kt
clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt

Make Media Control support double tap. When a double tap happens, media control trigger `DID_DOUBLE_TOUCH_MEDIA_CONTROL`.

Support double tap on media control

---

clappr/src/main/kotlin/io/clappr/player/base/Events.kt
clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt

Trigger `DID_LOOP` event  on Playback when video loop enabled and a loop happens.

Trigger DID_LOOP event when a loop happens

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/main/res/layout/media_control.xml
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt

Add a top center panel to media control.

Add top center panel to media control

---

clappr/src/main/kotlin/io/clappr/player/base/keys/Key.kt
clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/main/kotlin/io/clappr/player/plugin/core/externalinput/ExternalInputPlugin.kt
clappr/src/test/kotlin/io/clappr/player/plugin/ExternalInputPluginTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt

Show media control for supported keys from external inputs

Show Media Control on External Input Event

---

clappr/src/main/kotlin/io/clappr/player/components/Core.kt

Now core show have its own `SharedData` class
run unit test: `./gradlew clean test`

Add SharedDate on Core

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt

Add Blocked Key List to not show Media Control.
Run Unit Tests: `./gradlew clean test`

Add Blocked Key List to not show Media Control

---

clappr/build.gradle
clappr/src/test/kotlin/io/clappr/player/components/CoreTest.kt
clappr/src/test/kotlin/io/clappr/player/components/MediaOptionTest.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerExtensionsTest.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerUtil.kt

Update mockito-kotlin dependency to allow coroutines verification

Update mockito dependency

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt

Able to set background view property.

Open background view property

---

README.md
app/build.gradle
app/src/main/kotlin/io/clappr/player/app/plugin/VideoInfoPlugin.kt
build.gradle
clappr/build.gradle
clappr/src/main/kotlin/io/clappr/player/base/BaseObject.kt
clappr/src/main/kotlin/io/clappr/player/base/Events.kt
clappr/src/main/kotlin/io/clappr/player/plugin/LoadingPlugin.kt
clappr/src/main/kotlin/io/clappr/player/plugin/PosterPlugin.kt
clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
gradle.properties

Add Androidx support to clappr

Support AndroidX

---

README.md
build.gradle

This reverts commit 052d5b658ff6ce5fc21e2370905c469d183f591f.

Revert "chore: update kotlin version to 1.3.60 and android gradle plugin to 3.5.2"

---

app/build.gradle
app/src/main/kotlin/io/clappr/player/app/PlayerActivity.kt
clappr/src/main/kotlin/io/clappr/player/Player.kt

Remove deprecated fragments from clappr

Remove deprecated fragment

---

clappr/src/main/kotlin/io/clappr/player/base/Events.kt
clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayback.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerPlaybackTest.kt

Goal
---
`WILL_SEEK` event will now send the intended destination position
How to test
---
Listen to the will seek event and check the destination position.

Send position in WILL_SEEK bundle

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayback.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerPlaybackTest.kt

Fix subtitle visibility
Unit test should be sufficient

Hide subtitle when ExoplayerPlayback is initialized
