clappr/clappr-android

player/src/main/kotlin/io/clappr/player/components/Container.kt
player/src/main/kotlin/io/clappr/player/components/Core.kt
player/src/main/kotlin/io/clappr/player/plugin/LoadingPlugin.kt
player/src/main/kotlin/io/clappr/player/plugin/UIPlugin.kt

Rendering plugins is one of Core/Container responsibilities, so instead of letting the plugin handle appending itself to the component view tree, their render method should be called when Core/Container are rendering themselves.

Refactor plugin rendering

---

clappr/src/main/kotlin/io/clappr/player/Player.kt
clappr/src/test/java/io/clappr/player/PlayerJavaTest.java

I consider that Options (with named and default parameters) and Loader (requiring a KClass for registering playbacks and plugins) classes should also be revamped to provide a cleaner java interoperability.

Player java interoperability

---

clappr/src/main/kotlin/io/clappr/player/plugin/Loader.kt
clappr/src/main/kotlin/io/clappr/player/plugin/UIPlugin.kt

Also removing invalid plugin error log on Loader as it is expected due to the lack of constructor component type (e.g.: load a Container plugin with a Core parameter).

Plugin extensibility

---

clappr/src/main/kotlin/io/clappr/player/base/InternalEvents.kt
clappr/src/main/kotlin/io/clappr/player/components/Container.kt
clappr/src/test/kotlin/io/clappr/player/components/ContainerTest.kt

This PR adds two events when loading a new source
- WILL_LOAD_SOURCE
- DID_LOAD_SOURCE
- DID_NOT_LOAD_SOURCE
This will be useful for plugins to know when a new source is set.

Add load source events on container

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt

We are using AdaptiveMediaSource to listen just one event `onLoadError()` and the same don't represent a critical error to Exoplayer. The method `onLoadError()` is used when has the necessity of handle different media sources in same video, is not our case for while. Thus, we decide to remove it.

Remove AdaptiveMediaSource from Exoplayer

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt

Identify when the player start in DVR state while it is on pause.
1 - Load live video with DVR
2 - Pause video
3 - After few seconds check that the `DID_CHANGE_DVR_STATUS` was trigged.

Feature: Periodic DVR state  update 

---

clappr/src/main/kotlin/io/clappr/player/Player.kt

Fixes problem when a video live is not pausing when `onResume()` fragment method is called.
#How to test
1 - Play a live vide then click home buttom
2 - When return to activity the video should be stoped.

Fix playing live videos when in background

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/PlayButton.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/PlayButtonTest.kt

Improve Play Button listeners handling by stop listening Playback events when plugin is destroyed.
3 - Check if Play Button plugin is appearing in the video
4 - Pause and play the video

Improve Play Button Listeners Handling

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/FullscreenButton.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/FullscreenButtonTest.kt

Improve Fullscreen Button listeners handling by stop listening Playback events when plugin is destroyed.
3 - Check if Fullscreen Button plugin is appearing in the video
4 - Click in the Fullscreen button
5 - Check if the Player go fullscreen and the button icon changes
6 - Turn the device to check if the player go portrait and the button changes
7 - Seek to the end of the video
8 - Click in the Play button to restart the video
9 - Check if the Fullscreen button is working as expected

Improve Fullscreen Button Listeners Handling

---

app/src/main/kotlin/io/clappr/player/app/PlayerActivity.kt
app/src/main/res/layout/activity_player.xml
app/src/main/res/values/strings.xml
clappr/src/main/kotlin/io/clappr/player/plugin/LoadingPlugin.kt
clappr/src/test/kotlin/io/clappr/player/plugin/LoadingPluginTest.kt

Improve Loading Plugin listeners handling by stop listening Playback events when plugin is destroyed.
Start by running the Unit Tests
1 - Open sample app
2 - Check if Loading is appearing in the video
3 - Seek to the middle of the video and check if the loading appears
4 - Seek to the end of the video
5 - Click in the Play button to restart the video
6 - Check if Loading is appearing in the video
7 - Click in the `Change Video` button
8 - Check if a new video is loaded and the Loading is working as expected

Improve Loading Plugin Listeners Handling

---

clappr/src/main/kotlin/io/clappr/player/plugin/PosterPlugin.kt
clappr/src/test/kotlin/io/clappr/player/plugin/PosterPluginTest.kt

Goal
---
Improve PosterPlugin listeners handling by stop listening Playback events when plugin is destroyed.
How to Test
3 - Check if poster is appearing in the video
4 - Seek to the end of the video
5 - Check if poster is appearing in the video
6 - Click in the Play button to restart the video
7 - Check if poster is appearing in the video

feat/poster_listeners: remove liteners from PosterPlugin after destroying

---

clappr/src/main/kotlin/io/clappr/player/base/BaseObject.kt
clappr/src/main/kotlin/io/clappr/player/components/Container.kt
clappr/src/main/kotlin/io/clappr/player/components/Core.kt
clappr/src/main/kotlin/io/clappr/player/plugin/Loader.kt
clappr/src/test/kotlin/io/clappr/player/base/BaseObjectTest.kt
clappr/src/test/kotlin/io/clappr/player/components/ContainerTest.kt
clappr/src/test/kotlin/io/clappr/player/components/CoreTest.kt

Prevent Player crash when Plugin throw exception during event invocation.
To test this change we create a plugin that throws Exceptions. To add it in the project, open PlayerActivity.kt in sample app and add this class on top of PlayerActivity:
```kotlin
class BrokenPlugin(core: Core) : MediaControl.Plugin(core) {
companion object : NamedType {
override val name: String?
get() = "broken"
}
init {
listenTo(core, InternalEvent.DID_CHANGE_ACTIVE_PLAYBACK.value, Callback.wrap { throw NullPointerException("I destroyed your Player during Event") })
}
override fun destroy() {
throw NullPointerException("I destroyed your Player during Destroy")
}
override fun render() {
throw NullPointerException("I destroyed your Player during Render")
}
}
```
Then register the Plugin in the onCreate method of …

Prevent Player crash when Plugin throw exception

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt

Hide the media control when a new video will load.
Start by running the Unit Tests
1 - Open sample app
2 - Check if the video is playing
3 - Click on `Change Video`
4 - Check if media control was hidden and a new video is loading

Hide Media Control on WILL_LOAD_SOURCE

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt

1 - Load a video and Media Control should not shown
2 - Click on the screen and make sure that Media Control is there

Start to play a new video without show Media Control

---

app/src/main/kotlin/io/clappr/player/app/PlayerActivity.kt
app/src/main/kotlin/io/clappr/player/app/plugin/NextVideoPlugin.kt
app/src/main/kotlin/io/clappr/player/app/plugin/VideoInfoPlugin.kt
app/src/main/res/layout/activity_player.xml
app/src/main/res/layout/video_info_plugin.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/test/kotlin/io/clappr/player/app/plugin/NextVideoPluginTest.kt
app/src/test/kotlin/io/clappr/player/app/plugin/VideoInfoPluginTest.kt
app/src/test/kotlin/io/clappr/player/app/plugin/util/Extensions.kt
app/src/test/kotlin/io/clappr/player/app/plugin/util/FakePlayback.kt

Goal
----
Add external plugin to Player.
- `VideoInfoPlugin` is a `MediaControl.Plugin` to show title and subtitle if informed by Options
How to Test
----
- open clappr app
- for both fullscreen and embedded modes, every time media control is clicked, title should be shown.
- only on fullscreen mode, every time media control is clicked, subtitle should be shown.

Feature/sample plugins: VideoInfoPlugin

---

app/src/main/kotlin/io/clappr/player/app/PlayerActivity.kt
app/src/main/kotlin/io/clappr/player/app/plugin/NextVideoPlugin.kt
app/src/main/kotlin/io/clappr/player/app/plugin/PlaybackStatusPlugin.kt
app/src/main/kotlin/io/clappr/player/app/plugin/VideoInfoPlugin.kt
app/src/main/res/layout/playback_status_plugin.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/test/kotlin/io/clappr/player/app/plugin/PlaybackStatusPluginTest.kt

Goal
---
Add external plugin to Player.
`PlaybackStatePlugin` is a `UIContainerPlugin` to show status of current playback
How to Test
---
- open clappr app
- while loading video, should show `Playback Status: stalling`
- while playing video, should show `Playback Status: playing`
- after pause video, should show `Playback Status: didPause`
- after stop video, should show `Playback Status: didStop`
- after complete video, should show `Playback Status: didComplete`
- after an error, should show `Playback Status: error`

Feature/sample UIContainerPlugin

---

clappr/build.gradle
clappr/versioning.gradle

Android `versionName` and `versionCode` are not required in the `AndroidManifest` of an .aar library.

Remove version information from library

---

app/src/main/kotlin/io/clappr/player/app/plugin/NextVideoPlugin.kt
app/src/test/kotlin/io/clappr/player/app/plugin/NextVideoPluginTest.kt
app/src/test/kotlin/io/clappr/player/app/plugin/PlaybackStatusPluginTest.kt
app/src/test/kotlin/io/clappr/player/app/plugin/VideoInfoPluginTest.kt
app/src/test/kotlin/io/clappr/player/app/plugin/assertPlugin/assertUiPlugin.kt

Sometimes `NextVideoPlugin` is shown behind Media Control and is not touchable. This PR make sure that when  `NextVideoPlugin` is shown, it will be on top of `Core` views.
- Play a video until it ends and make sure you can choose next video.

Make sure show NextVideoPlugin above another UiCorePlugins

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt

Removed an API 18 dependency from Exoplayer Playback code.
How to test:
1. Run the application on an API 16 or 17 emulator

Fix crash on Jelly Bean	(API 16 an 17) phones

---

clappr/build.gradle
clappr/src/main/kotlin/io/clappr/player/base/InternalEvents.kt
clappr/src/main/kotlin/io/clappr/player/components/Core.kt
clappr/src/test/kotlin/io/clappr/player/components/CoreTest.kt

Trigger resize event when core view change size.
- Run tests on `clappr` module
To test this feature add this plugin to the PlayerActivity in the sample app:
```kotlin
class ResizePlugin(core: Core) : CorePlugin(core, name=name) {
companion object : NamedType {
override val name = "resizePlugin"
val entry = PluginEntry.Core(name = name, factory = { core -> ResizePlugin(core) })
}
init { listenTo(core, InternalEvent.DID_RESIZE.value) { Log.d(name, "Did Resize was called") } }
}
```
Then register the plugin before the Player instantiation in the onCreate method:
```kotlin
Loader.register(ResizePlugin.entry)
player = Player()
```
- Open sample app
- Filter the log by `resizePlugin`
- You should see the message `Did Resize was called` the first time the Player is render
- Click in the …

Trigger Resize Event

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerPlayBackTest.kt

Whenever the method `seekToLivePosition()` of `ExoPlayerPlayback` is called the events `WILL_SEEK`, `DID_SEEK` and `DID_UPDATE_POSITION` must be triggered to notify all corresponding changes that will be executed on the player
Run player unit tests: `./gradlew clean test`

Fix: Trigger seek events when seekToLivePosition is called

---

clappr/src/main/kotlin/io/clappr/player/Player.kt
clappr/src/main/kotlin/io/clappr/player/base/Events.kt
clappr/src/main/kotlin/io/clappr/player/base/InternalEvents.kt
clappr/src/main/kotlin/io/clappr/player/components/Playback.kt
clappr/src/test/kotlin/io/clappr/player/PlayerTest.kt
clappr/src/test/kotlin/io/clappr/player/components/PlaybackTest.kt

Fix remove some playback responsibility. The playback should trigger `MEDIA_OPTIONS_UPDATE` event only, after a media option update. 
Run player unit tests: `./gradlew clean test`

Fix: Playback media options

---

clappr/src/main/kotlin/io/clappr/player/Player.kt
clappr/src/test/kotlin/io/clappr/player/PlayerTest.kt

The Media Options Selected event must be fired externally to the Player when it is triggered by the Core.
Run player unit tests: `./gradlew clean test`

Trigger MEDIA_OPTIONS_SELECTED  event externally to the Player

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt

Reset Media Control state when a new source is loaded.
Run Unit Tests: `./gradlew clean test`
1 - Open sample app
2 - Play video and ensure Media Control is working as expected

Fix: Reset Media Control State

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt

Actually it is possible `seek` in a video when it is complete, however, the seek is not done by Exoplayer. This behavior create several problems with plugins that use `canSeek` Playback propertie since Exoplayer return that it is possible to seek but it don't. This PR make `canSeek` property return false when video is compleater.

Disable seek when video is complete

---

clappr/src/main/kotlin/io/clappr/player/base/Options.kt
clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayBack.kt

Enable Audio Focus handling via ExoPlayer. The feature can be enabled by the HANDLE_AUDIO_FOCUS option and is disabled by default.
Default ExoPlayer behavior is playback's volume being diminished after audio focus loss and restored after regaining focus.
- Run unit tests: `./gradlew clean test`

Audio Focus

---

clappr/src/main/kotlin/io/clappr/player/Player.kt
clappr/src/main/kotlin/io/clappr/player/base/Events.kt
clappr/src/main/kotlin/io/clappr/player/base/keys/Action.kt
clappr/src/main/kotlin/io/clappr/player/base/keys/Key.kt
clappr/src/main/kotlin/io/clappr/player/plugin/core/externalinput/ExternalInputDevice.kt
clappr/src/main/kotlin/io/clappr/player/plugin/core/externalinput/ExternalInputPlugin.kt
clappr/src/test/kotlin/io/clappr/player/PlayerTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/ExternalInputPluginTest.kt

Add external input devices support  such as TV's remote controls, Video Game Controls and others.
Initialy support `PLAY`, `PAUSE`, `STOP` and `PLAY_PAUSE` buttons.

External Input Devices Support

---

clappr/src/main/kotlin/io/clappr/player/Player.kt

Add destroy method on player instance, so we can recreate core on configure call.
1 - Run unit tests: `./gradlew clean test`

Destroy core from player

---

clappr/src/main/kotlin/io/clappr/player/Player.kt
clappr/src/main/kotlin/io/clappr/player/base/Events.kt
clappr/src/main/kotlin/io/clappr/player/base/InternalEvents.kt
clappr/src/main/kotlin/io/clappr/player/base/Options.kt
clappr/src/main/kotlin/io/clappr/player/components/MediaOption.kt
clappr/src/main/kotlin/io/clappr/player/components/Playback.kt
clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerExtensions.kt
clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayback.kt
clappr/src/test/kotlin/io/clappr/player/PlayerTest.kt
clappr/src/test/kotlin/io/clappr/player/components/MediaOptionTest.kt
clappr/src/test/kotlin/io/clappr/player/components/PlaybackTest.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerExtensionsTest.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerPlaybackTest.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerUtil.kt
clappr/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

This PR removes all `MediaOptions` dependency. 
This should make easier to handle:
- Available audios and subtitles 
- Selected audio and subtitle
1 - run player unit tests: .`/gradlew clean test`

Remove media options

---

clappr/src/main/kotlin/io/clappr/player/Player.kt
clappr/src/main/kotlin/io/clappr/player/base/keys/Key.kt
clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/main/kotlin/io/clappr/player/plugin/core/externalinput/ExternalInputPlugin.kt
clappr/src/test/kotlin/io/clappr/player/plugin/ExternalInputPluginTest.kt

Add support for remote control's back key and add core events list to Player's constructor following same pattern used for playback and container events.
- Run unit tests: `./gradlew clean test`

Handle Remote Control's Back Key

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt

Goal
---
In some specific situations Media Control animations do not behave as they should and flash rapidly. This occur in two scenarios:
1. The problem occurs when the Modal tries to hide it self even though it is not open at the beginning of the video. The animation changes the alpha of the component that appears briefly on the screen and then hides again.
2. The problem is due to using `postDelayed` to hide Media Control after a delay. When Media Control is opened a new post is performed to close it, if this operation is performed several times in sequence in a short period of time the old posts are executed at an unexpected time. The `postDelayed` performs Media Control's hide animation that alters the component's alpha so that appears briefly on the screen and then hides again …

Fix Media Control Blinking Animations

---

clappr/src/main/kotlin/io/clappr/player/extensions/BundleExtensions.kt
clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/test/kotlin/io/clappr/player/extensions/BundleExtensionsTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt

Make Media Control visible when playback is idle. Now, when stop method is called, the media control will show up and if the video starts to play again, it will be hidden with fade out time.
Also, a Bundle extension function was created to get remote control key and action.
Run player unit tests: ./gradlew clean test

Handle media control visibilty when video stop playing

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayback.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerPlaybackTest.kt

Goal
---
Fixes duration calculation for Live videos with DVR
Context
---
The duration of live videos with DVR was not discounting the syncBufferInSeconds (20s as default) as it should.

Fixes duration calculation for Live videos with DVR

---

clappr/src/main/res/layout/media_control.xml

Fixes Media Control plugins placed in panel `Top` with position `Right` that were placed in position `Left`.

Fix top right plugins positions on Media Control

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt

Goal
---
When we show the Media Control we schedule a hide, however this handler can still run even when the Media Control is already hidden. So is important to clear the handler when Media Control is already hidden.
How to Test
---
Run unit tests: `./gradlew clean test`

Clear hide handler when Media Control is already hidden

---

clappr/src/main/kotlin/io/clappr/player/base/Events.kt
clappr/src/main/kotlin/io/clappr/player/extensions/BundleExtensions.kt
clappr/src/main/kotlin/io/clappr/player/plugin/core/externalinput/ExternalInputPlugin.kt
clappr/src/test/kotlin/io/clappr/player/extensions/BundleExtensionsTest.kt
clappr/src/test/kotlin/io/clappr/player/plugin/ExternalInputPluginTest.kt

Goal
---
Add Long Press information to external input event. The long press is sent as a boolean in the event bundle.
How to Test
---
Run unit tests: `./gradlew clean test`

Add Long Press Information to external input event

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt
clappr/src/test/kotlin/io/clappr/player/shadows/ClapprShadowView.kt
clappr/src/test/kotlin/io/clappr/player/shadows/ClapprShadowViewGroup.kt

Goal
---
When a double tap is performed and the video is paused the Media Control is being shown. The Media Control should not show after a double tap.
How to Test
---
Run Unit Tests: `./gradlew clean test`

Fix: Media Control Show After Double Tap When Video Is Paused

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/MediaControl.kt
clappr/src/main/res/layout/media_control.xml
clappr/src/test/kotlin/io/clappr/player/plugin/control/MediaControlTest.kt

Position top center plugin panel correctly.
1 - After
2 - Before
1 - Create the following plugin:
```
class PluginCastButton(core: Core) : ButtonPlugin(core, name) {
companion object : NamedType {
override val name = "pluginCastButton"
val entry = PluginEntry.Core(name = name, factory = { core -> PluginCastButton(core) })
}
override var panel: Panel = Panel.TOP
override var position: Position = Position.CENTER
override val resourceDrawable: Int
get() = R.drawable.fullscreen_button
override val idResourceDrawable: Int
get() = R.id.fullscreen_button
override val resourceLayout: Int
get() = R.layout.button_plugin
override fun onClick() {
core.activePlayback?.stop()
}
}
```
2 - Register this plugin in `BaseConfigPlugin`:
`Loader.register(PluginCastButton.entry)`

Fix plugin top center position

---

clappr/src/main/kotlin/io/clappr/player/base/Events.kt
clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayback.kt
clappr/src/main/kotlin/io/clappr/player/playback/VideoResolutionChangeListener.kt
clappr/src/main/kotlin/io/clappr/player/utils/BundleExtensions.kt
clappr/src/test/kotlin/io/clappr/player/playback/VideoResolutionChangeListenerTest.kt

Goal
---
Add the capability to monitor updates to video resolution during video playback
How to test
---
Inside a plugin, Listen to the playback `DID_UPDATE_VIDEO_RESOLUTION` and log its bundle contents.
You can also force a resolution change by tempering with the emulator's bandwidth.

Did update video resolution

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerBitrateHandler.kt
clappr/src/main/kotlin/io/clappr/player/playback/VideoResolutionChangeListener.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerBitrateHandlerTest.kt

Goal 
---
Replace AnalyticsListener with EventLogger in order to avoid AbstractMethodError caused by java/kotlin interoperability

Replace AnalyticsListener with EventLogger

---

clappr/src/main/kotlin/io/clappr/player/playback/ExoPlayerPlayback.kt
clappr/src/test/kotlin/io/clappr/player/playback/ExoPlayerPlaybackTest.kt

- Improve the state machine to report event related events after seek (playing, did_pause and stalling)
- Improve the state machine to report stalling events after will_pause when video is paused during stalling state

State machine enhancements on seek

---

clappr/src/main/kotlin/io/clappr/player/plugin/control/TimeIndicatorPlugin.kt
clappr/src/main/res/layout/time_indicator.xml

- Set ID for TextView TimeIndicator in order to check visibility in instrumentation tests

Set id for TextView TimeIndicator
